version: "3"

networks:
  loki:

services:
  web_app:
    hostname: web_app
    image: ign19ht/dev-ops-labs:latest
    restart: always
    ports:
      - "8000:8000"
    command: python3 main.py
    logging: &default_logging
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    deploy:
      resources:
        limits:
          memory: 512M

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      <<: *default_logging
    deploy:
      resources:
        limits:
          memory: 512M

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging:
      <<: *default_logging
    deploy:
      resources:
        limits:
          memory: 512M

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - loki
    logging:
      <<: *default_logging
    deploy:
      resources:
        limits:
          memory: 512M

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/ds.yml
    networks:
      - loki
    logging:
      <<: *default_logging
    deploy:
      resources:
        limits:
          memory: 512M

