apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app.kubernetes.io/name: python-app
  name: python-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: python-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-app
    spec:
      containers:
      - name: python-app
        image: ign19ht/dev-ops-labs:latest
        ports:
        - containerPort: 8000
        command: ['python3']
        args: ['main.py']
