name: App Workflow

on: [push]

jobs:

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.19'
      - name: Snyk test
        run: |
          cd app_python 
          pip install -r requirements.txt
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd app_python
          pip install -r requirements.txt
      - name: Python Linter
        run: |
          cd app_python
          pip install -r requirements.txt
          pip install pylint
          python -m pylint src/main.py 
      - name: Test
        run: |
          cd app_python
          python -m unittest tests.test

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app_python
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dev-ops-labs:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dev-ops-labs:latest-buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dev-ops-labs:latest-buildcache,mode=max